[env:m5dial]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DWM_STRINGS_FILE="\"wm_strings_es.h\""
lib_deps =
  https://github.com/m5stack/M5GFX.git#0.2.9
  https://github.com/m5stack/M5Unified.git#0.2.7
  https://github.com/m5stack/M5Dial.git#1.0.3
  https://github.com/tzapu/WiFiManager.git#v2.0.17
  https://github.com/bblanchon/ArduinoJson.git#v7.2.1
