#!/usr/bin/env bash
# Concatenates every migration into supabase/setup-all.sql, wrapped in one
# transaction, for pasting into the Supabase dashboard SQL Editor when the
# Supabase CLI isn't available. Regenerate after adding a migration.
set -euo pipefail
cd "$(dirname "$0")/.."
out=supabase/setup-all.sql
{
  echo "-- GENERATED by scripts/build-setup-sql.sh — do not edit by hand."
  echo "-- Paste into Supabase Dashboard -> SQL Editor -> Run, ONCE, on an empty project."
  echo "-- Runs in a single transaction: if anything fails, nothing is applied."
  echo
  echo "begin;"
  for f in supabase/migrations/*.sql; do
    echo
    echo "-- ===================================================================="
    echo "-- $(basename "$f")"
    echo "-- ===================================================================="
    cat "$f"
  done
  echo
  echo "commit;"
} > "$out"
echo "wrote $out"
