-- GENERATED by scripts/build-setup-sql.sh - do not edit by hand.
-- Paste into Supabase Dashboard -> SQL Editor -> Run, ONCE, on an empty project.
-- Runs in a single transaction: if anything fails, nothing is applied.

begin;

-- ====================================================================
-- 20260926000001_tenancy.sql
-- ====================================================================
-- Tenancy & identity: schools, profiles, per-school role memberships, and the
-- SECURITY DEFINER helpers that every RLS policy is built on.
--
-- Conventions used by every migration:
--   * Every tenant-owned table has `school_id` and `unique (school_id, id)`, and
--     children reference parents with composite FKs `(school_id, parent_id)`,
--     so a row can never point at another school's data.
--   * All instants are timestamptz; wall-clock times are interpreted in
--     schools.timezone.
--   * `app` schema holds private helpers; it is not exposed through the API.

create schema if not exists app;
revoke all on schema app from public;
grant usage on schema app to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
create type public.school_status as enum ('active', 'suspended');
create type public.membership_role as enum ('school_admin', 'teacher', 'student');
create type public.membership_status as enum ('invited', 'active', 'disabled');

-- ---------------------------------------------------------------------------
-- Shared trigger: updated_at
-- ---------------------------------------------------------------------------
create function app.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create function app.is_valid_timezone(tz text)
returns boolean
language sql
stable
set search_path = ''
as $$
  select exists (select 1 from pg_catalog.pg_timezone_names where name = tz);
$$;

-- ---------------------------------------------------------------------------
-- schools
-- ---------------------------------------------------------------------------
create table public.schools (
  id          uuid primary key default gen_random_uuid(),
  name        text not null check (length(trim(name)) between 1 and 200),
  slug        text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and length(slug) <= 63),
  timezone    text not null default 'America/Bogota' check (app.is_valid_timezone(timezone)),
  locale      text not null default 'es-CO',
  status      public.school_status not null default 'active',
  settings    jsonb not null default '{}'::jsonb check (jsonb_typeof(settings) = 'object'),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create trigger schools_updated_at before update on public.schools
  for each row execute function app.set_updated_at();

-- ---------------------------------------------------------------------------
-- profiles (1:1 with auth.users). Holds no school or role information.
-- ---------------------------------------------------------------------------
create table public.profiles (
  id                 uuid primary key references auth.users (id) on delete cascade,
  email              text,
  full_name          text not null default '',
  is_platform_admin  boolean not null default false,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create trigger profiles_updated_at before update on public.profiles
  for each row execute function app.set_updated_at();

create function app.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function app.handle_new_auth_user();

-- ---------------------------------------------------------------------------
-- school_memberships: the ONLY source of truth for roles.
-- ---------------------------------------------------------------------------
create table public.school_memberships (
  id          uuid primary key default gen_random_uuid(),
  school_id   uuid not null references public.schools (id) on delete cascade,
  user_id     uuid not null references public.profiles (id) on delete cascade,
  role        public.membership_role not null,
  status      public.membership_status not null default 'active',
  invited_by  uuid references public.profiles (id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (school_id, user_id, role)
);

create index school_memberships_user_idx on public.school_memberships (user_id);

create trigger school_memberships_updated_at before update on public.school_memberships
  for each row execute function app.set_updated_at();

-- ---------------------------------------------------------------------------
-- Authorization helpers.
--
-- SECURITY DEFINER so policies can consult school_memberships without
-- recursing into school_memberships' own RLS. search_path is pinned and every
-- object is schema-qualified.
-- ---------------------------------------------------------------------------
create function app.is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select p.is_platform_admin from public.profiles p where p.id = auth.uid()),
    false
  );
$$;

create function app.has_role(p_school_id uuid, p_role public.membership_role)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.school_memberships m
    where m.school_id = p_school_id
      and m.user_id = auth.uid()
      and m.role = p_role
      and m.status = 'active'
  );
$$;

create function app.is_member(p_school_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.school_memberships m
    where m.school_id = p_school_id
      and m.user_id = auth.uid()
      and m.status = 'active'
  );
$$;

create function app.is_admin(p_school_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select app.has_role(p_school_id, 'school_admin');
$$;

revoke all on all functions in schema app from public;
grant execute on function
  app.is_platform_admin(),
  app.has_role(uuid, public.membership_role),
  app.is_member(uuid),
  app.is_admin(uuid),
  app.is_valid_timezone(text)
to authenticated, service_role;

-- ====================================================================
-- 20260926000002_people.sql
-- ====================================================================
-- People: students and teachers belong to exactly one school.

create type public.student_status as enum ('active', 'inactive', 'graduated', 'withdrawn');
create type public.teacher_status as enum ('active', 'inactive');

-- ---------------------------------------------------------------------------
-- students. A login (user_id) is optional: young students may never have one.
-- ---------------------------------------------------------------------------
create table public.students (
  id              uuid primary key default gen_random_uuid(),
  school_id       uuid not null references public.schools (id) on delete cascade,
  user_id         uuid references public.profiles (id) on delete set null,
  student_number  text not null check (length(trim(student_number)) between 1 and 64),
  first_name      text not null check (length(trim(first_name)) between 1 and 100),
  last_name       text not null check (length(trim(last_name)) between 1 and 100),
  grade_level     text,
  status          public.student_status not null default 'active',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (school_id, id),
  unique (school_id, student_number),
  unique (school_id, user_id)
);

create index students_user_idx on public.students (user_id) where user_id is not null;

create trigger students_updated_at before update on public.students
  for each row execute function app.set_updated_at();

-- ---------------------------------------------------------------------------
-- teachers. Always tied to a login; authorization additionally requires an
-- active 'teacher' membership in the same school (see app.teaches_class).
-- ---------------------------------------------------------------------------
create table public.teachers (
  id               uuid primary key default gen_random_uuid(),
  school_id        uuid not null references public.schools (id) on delete cascade,
  user_id          uuid not null references public.profiles (id) on delete restrict,
  employee_number  text,
  first_name       text not null check (length(trim(first_name)) between 1 and 100),
  last_name        text not null check (length(trim(last_name)) between 1 and 100),
  status           public.teacher_status not null default 'active',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (school_id, id),
  unique (school_id, user_id),
  unique (school_id, employee_number)
);

create index teachers_user_idx on public.teachers (user_id);

create trigger teachers_updated_at before update on public.teachers
  for each row execute function app.set_updated_at();

-- A student row may only be linked to a login that holds a 'student'
-- membership in the same school, and a teacher row to a 'teacher' membership.
-- This stops an admin from attaching an arbitrary account to their school's
-- records and so granting it access.
create function app.check_person_membership()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role public.membership_role :=
    case tg_table_name when 'students' then 'student' else 'teacher' end;
begin
  if new.user_id is not null and not exists (
    select 1 from public.school_memberships m
    where m.school_id = new.school_id
      and m.user_id = new.user_id
      and m.role = v_role
  ) then
    raise exception 'user % has no % membership in school %', new.user_id, v_role, new.school_id
      using errcode = 'foreign_key_violation';
  end if;
  return new;
end;
$$;

create trigger students_membership_check
  before insert or update of user_id, school_id on public.students
  for each row execute function app.check_person_membership();

create trigger teachers_membership_check
  before insert or update of user_id, school_id on public.teachers
  for each row execute function app.check_person_membership();

-- ====================================================================
-- 20260926000003_academics.sql
-- ====================================================================
-- Academic structure: attendance rules, terms, courses, class sections,
-- teacher assignments, enrollments, recurring schedules and dated sessions.

create type public.scan_after_cutoff as enum ('late', 'absent', 'reject');
create type public.class_status as enum ('active', 'archived');
create type public.class_teacher_role as enum ('primary', 'assistant', 'substitute');
create type public.session_status as enum ('scheduled', 'cancelled', 'completed');

-- ---------------------------------------------------------------------------
-- attendance_rules. Minutes are relative to a session's starts_at.
--   scan at or before starts_at + late_after_minutes   -> present
--   scan at or before starts_at + absent_after_minutes -> late
--   later scans                                        -> scan_after_cutoff
--   no scan by starts_at + absent_after_minutes        -> absent (finalizer)
-- ---------------------------------------------------------------------------
create table public.attendance_rules (
  id                        uuid primary key default gen_random_uuid(),
  school_id                 uuid not null references public.schools (id) on delete cascade,
  name                      text not null check (length(trim(name)) between 1 and 100),
  is_default                boolean not null default false,
  early_checkin_minutes     integer not null default 10 check (early_checkin_minutes between 0 and 240),
  late_after_minutes        integer not null default 5 check (late_after_minutes between 0 and 240),
  absent_after_minutes      integer not null default 20 check (absent_after_minutes between 0 and 480),
  scan_after_cutoff         public.scan_after_cutoff not null default 'late',
  duplicate_window_seconds  integer not null default 60 check (duplicate_window_seconds between 0 and 3600),
  auto_finalize             boolean not null default true,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),
  unique (school_id, id),
  unique (school_id, name),
  check (absent_after_minutes >= late_after_minutes)
);

create unique index attendance_rules_one_default_per_school
  on public.attendance_rules (school_id) where is_default;

create trigger attendance_rules_updated_at before update on public.attendance_rules
  for each row execute function app.set_updated_at();

-- ---------------------------------------------------------------------------
-- academic_terms
-- ---------------------------------------------------------------------------
create table public.academic_terms (
  id          uuid primary key default gen_random_uuid(),
  school_id   uuid not null references public.schools (id) on delete cascade,
  name        text not null check (length(trim(name)) between 1 and 100),
  starts_on   date not null,
  ends_on     date not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (school_id, id),
  unique (school_id, name),
  check (ends_on >= starts_on)
);

create trigger academic_terms_updated_at before update on public.academic_terms
  for each row execute function app.set_updated_at();

-- ---------------------------------------------------------------------------
-- courses (the subject, e.g. "Mathematics 7")
-- ---------------------------------------------------------------------------
create table public.courses (
  id           uuid primary key default gen_random_uuid(),
  school_id    uuid not null references public.schools (id) on delete cascade,
  code         text not null check (length(trim(code)) between 1 and 32),
  name         text not null check (length(trim(name)) between 1 and 200),
  description  text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (school_id, id),
  unique (school_id, code)
);

create trigger courses_updated_at before update on public.courses
  for each row execute function app.set_updated_at();

-- ---------------------------------------------------------------------------
-- class_sections ("the class" teachers teach and students enroll in)
-- ---------------------------------------------------------------------------
create table public.class_sections (
  id                  uuid primary key default gen_random_uuid(),
  school_id           uuid not null references public.schools (id) on delete cascade,
  course_id           uuid not null,
  term_id             uuid,
  name                text not null check (length(trim(name)) between 1 and 200),
  room                text,
  attendance_rule_id  uuid,
  status              public.class_status not null default 'active',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (school_id, id),
  foreign key (school_id, course_id) references public.courses (school_id, id),
  foreign key (school_id, term_id) references public.academic_terms (school_id, id),
  foreign key (school_id, attendance_rule_id) references public.attendance_rules (school_id, id)
);

create index class_sections_course_idx on public.class_sections (school_id, course_id);

create trigger class_sections_updated_at before update on public.class_sections
  for each row execute function app.set_updated_at();

-- ---------------------------------------------------------------------------
-- class_teachers (many-to-many; supports dated substitutes)
-- ---------------------------------------------------------------------------
create table public.class_teachers (
  id                uuid primary key default gen_random_uuid(),
  school_id         uuid not null references public.schools (id) on delete cascade,
  class_section_id  uuid not null,
  teacher_id        uuid not null,
  role              public.class_teacher_role not null default 'primary',
  valid_from        date,
  valid_to          date,
  created_at        timestamptz not null default now(),
  unique (school_id, id),
  unique (class_section_id, teacher_id),
  foreign key (school_id, class_section_id) references public.class_sections (school_id, id) on delete cascade,
  foreign key (school_id, teacher_id) references public.teachers (school_id, id) on delete cascade,
  check (valid_to is null or valid_from is null or valid_to >= valid_from)
);

create index class_teachers_teacher_idx on public.class_teachers (teacher_id);

-- ---------------------------------------------------------------------------
-- enrollments (dated, so mid-term joiners are not marked absent retroactively)
-- ---------------------------------------------------------------------------
create table public.enrollments (
  id                uuid primary key default gen_random_uuid(),
  school_id         uuid not null references public.schools (id) on delete cascade,
  class_section_id  uuid not null,
  student_id        uuid not null,
  enrolled_on       date not null default current_date,
  withdrawn_on      date,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (school_id, id),
  foreign key (school_id, class_section_id) references public.class_sections (school_id, id) on delete cascade,
  foreign key (school_id, student_id) references public.students (school_id, id) on delete cascade,
  check (withdrawn_on is null or withdrawn_on >= enrolled_on)
);

create unique index enrollments_one_open_per_student
  on public.enrollments (class_section_id, student_id) where withdrawn_on is null;
create index enrollments_student_idx on public.enrollments (student_id);

create trigger enrollments_updated_at before update on public.enrollments
  for each row execute function app.set_updated_at();

-- ---------------------------------------------------------------------------
-- class_schedules: recurring rule in school-local wall-clock time.
-- ---------------------------------------------------------------------------
create table public.class_schedules (
  id                uuid primary key default gen_random_uuid(),
  school_id         uuid not null references public.schools (id) on delete cascade,
  class_section_id  uuid not null,
  weekday           smallint not null check (weekday between 1 and 7), -- ISO: 1 = Monday
  start_time        time not null,
  end_time          time not null,
  valid_from        date not null,
  valid_to          date,
  room              text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (school_id, id),
  foreign key (school_id, class_section_id) references public.class_sections (school_id, id) on delete cascade,
  check (end_time > start_time),
  check (valid_to is null or valid_to >= valid_from)
);

create index class_schedules_class_idx on public.class_schedules (class_section_id);

create trigger class_schedules_updated_at before update on public.class_schedules
  for each row execute function app.set_updated_at();

-- ---------------------------------------------------------------------------
-- class_sessions: concrete dated occurrences. Attendance hangs off these.
-- rule_snapshot freezes the effective attendance rule when the session opens
-- so later rule edits don't retroactively change results.
-- ---------------------------------------------------------------------------
create table public.class_sessions (
  id                uuid primary key default gen_random_uuid(),
  school_id         uuid not null references public.schools (id) on delete cascade,
  class_section_id  uuid not null,
  schedule_id       uuid,
  starts_at         timestamptz not null,
  ends_at           timestamptz not null,
  room              text,
  status            public.session_status not null default 'scheduled',
  cancelled_reason  text,
  rule_snapshot     jsonb,
  finalized_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (school_id, id),
  unique (schedule_id, starts_at),
  foreign key (school_id, class_section_id) references public.class_sections (school_id, id) on delete cascade,
  foreign key (school_id, schedule_id) references public.class_schedules (school_id, id) on delete set null (schedule_id),
  check (ends_at > starts_at)
);

create index class_sessions_school_time_idx on public.class_sessions (school_id, starts_at);
create index class_sessions_class_time_idx on public.class_sessions (class_section_id, starts_at);

create trigger class_sessions_updated_at before update on public.class_sessions
  for each row execute function app.set_updated_at();

-- ====================================================================
-- 20260926000004_attendance.sql
-- ====================================================================
-- Attendance: devices (readers + simulator), NFC credentials, raw scan log,
-- current attendance records, and the append-only audit log.

create type public.device_kind as enum ('reader', 'simulator');
create type public.device_status as enum ('active', 'disabled');
create type public.credential_status as enum ('active', 'lost', 'revoked');
create type public.attendance_status as enum ('present', 'late', 'absent', 'excused');
create type public.attendance_source as enum ('nfc', 'manual', 'system');
create type public.actor_type as enum ('user', 'device', 'system');
create type public.scan_outcome as enum (
  'recorded',
  'duplicate',
  'unknown_credential',
  'inactive_credential',
  'inactive_student',
  'no_active_session',
  'not_enrolled',
  'too_early',
  'after_cutoff',
  'device_disabled',
  'school_suspended'
);

-- ---------------------------------------------------------------------------
-- devices. Every scan comes from a device; the simulator is a device too.
-- token_hash = sha256 hex of the bearer token; the token itself is never stored.
-- ---------------------------------------------------------------------------
create table public.devices (
  id                uuid primary key default gen_random_uuid(),
  school_id         uuid not null references public.schools (id) on delete cascade,
  name              text not null check (length(trim(name)) between 1 and 100),
  kind              public.device_kind not null default 'reader',
  status            public.device_status not null default 'active',
  location          text,
  room              text,
  class_section_id  uuid,
  token_hash        text unique check (token_hash is null or token_hash ~ '^[0-9a-f]{64}$'),
  token_last4       text,
  last_seen_at      timestamptz,
  metadata          jsonb not null default '{}'::jsonb,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (school_id, id),
  foreign key (school_id, class_section_id) references public.class_sections (school_id, id) on delete set null (class_section_id)
);

create unique index devices_one_simulator_per_school
  on public.devices (school_id) where kind = 'simulator';

create trigger devices_updated_at before update on public.devices
  for each row execute function app.set_updated_at();

-- ---------------------------------------------------------------------------
-- nfc_credentials. uid_normalized = uppercase hex, no separators, 4/7/10 bytes.
-- One ACTIVE credential per UID per school; revoked/lost rows are history.
-- ---------------------------------------------------------------------------
create table public.nfc_credentials (
  id              uuid primary key default gen_random_uuid(),
  school_id       uuid not null references public.schools (id) on delete cascade,
  student_id      uuid not null,
  uid_normalized  text not null check (uid_normalized ~ '^([0-9A-F]{8}|[0-9A-F]{14}|[0-9A-F]{20})$'),
  label           text,
  status          public.credential_status not null default 'active',
  issued_at       timestamptz not null default now(),
  revoked_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (school_id, id),
  foreign key (school_id, student_id) references public.students (school_id, id) on delete cascade,
  check ((status = 'active') = (revoked_at is null))
);

create unique index nfc_credentials_active_uid
  on public.nfc_credentials (school_id, uid_normalized) where status = 'active';
create index nfc_credentials_student_idx on public.nfc_credentials (student_id);

create trigger nfc_credentials_updated_at before update on public.nfc_credentials
  for each row execute function app.set_updated_at();

-- ---------------------------------------------------------------------------
-- attendance_records: the current answer, one row per student per session.
-- unique (class_session_id, student_id) is the core duplicate guard.
-- ---------------------------------------------------------------------------
create table public.attendance_records (
  id                   uuid primary key default gen_random_uuid(),
  school_id            uuid not null references public.schools (id) on delete cascade,
  class_session_id     uuid not null,
  student_id           uuid not null,
  status               public.attendance_status not null,
  source               public.attendance_source not null,
  checked_in_at        timestamptz,
  first_scan_event_id  uuid,
  is_manual_override   boolean not null default false,
  note                 text,
  version              integer not null default 1,
  updated_by           uuid references public.profiles (id) on delete set null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (school_id, id),
  unique (class_session_id, student_id),
  foreign key (school_id, class_session_id) references public.class_sessions (school_id, id) on delete cascade,
  foreign key (school_id, student_id) references public.students (school_id, id) on delete cascade
);

create index attendance_records_student_idx on public.attendance_records (student_id, created_at desc);

create function app.bump_attendance_version()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end;
$$;

create trigger attendance_records_version before update on public.attendance_records
  for each row execute function app.bump_attendance_version();

-- ---------------------------------------------------------------------------
-- scan_events: append-only log of every tap, including rejected ones.
-- (device_id, idempotency_key) makes network retries safe; `response` holds
-- the exact API response so a retry can be replayed.
-- ---------------------------------------------------------------------------
create table public.scan_events (
  id                    uuid primary key default gen_random_uuid(),
  school_id             uuid not null references public.schools (id) on delete cascade,
  device_id             uuid not null,
  idempotency_key       text not null check (length(idempotency_key) between 8 and 128),
  uid_normalized        text not null,
  credential_id         uuid,
  student_id            uuid,
  class_session_id      uuid,
  attendance_record_id  uuid,
  device_scanned_at     timestamptz,
  received_at           timestamptz not null default now(),
  effective_at          timestamptz not null,
  outcome               public.scan_outcome not null,
  outcome_detail        text,
  response              jsonb,
  request_id            text,
  unique (school_id, id),
  unique (device_id, idempotency_key),
  foreign key (school_id, device_id) references public.devices (school_id, id),
  foreign key (school_id, credential_id) references public.nfc_credentials (school_id, id),
  foreign key (school_id, student_id) references public.students (school_id, id),
  foreign key (school_id, class_session_id) references public.class_sessions (school_id, id),
  foreign key (school_id, attendance_record_id) references public.attendance_records (school_id, id)
);

create index scan_events_school_time_idx on public.scan_events (school_id, received_at desc);
create index scan_events_debounce_idx on public.scan_events (device_id, uid_normalized, received_at desc);
create index scan_events_session_idx on public.scan_events (class_session_id) where class_session_id is not null;

alter table public.attendance_records
  add foreign key (school_id, first_scan_event_id) references public.scan_events (school_id, id);

-- ---------------------------------------------------------------------------
-- audit_logs: append-only, written by triggers (and later by RPCs).
-- ---------------------------------------------------------------------------
create table public.audit_logs (
  id               uuid primary key default gen_random_uuid(),
  school_id        uuid not null references public.schools (id) on delete cascade,
  actor_type       public.actor_type not null,
  actor_user_id    uuid references public.profiles (id) on delete set null,
  actor_device_id  uuid,
  action           text not null,
  entity_type      text not null,
  entity_id        uuid not null,
  before           jsonb,
  after            jsonb,
  reason           text,
  request_id       text,
  created_at       timestamptz not null default now()
);

create index audit_logs_school_time_idx on public.audit_logs (school_id, created_at desc);
create index audit_logs_entity_idx on public.audit_logs (entity_type, entity_id);

create function app.prevent_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception '% is append-only', tg_table_name using errcode = 'insufficient_privilege';
end;
$$;

create trigger audit_logs_append_only before update or delete on public.audit_logs
  for each row execute function app.prevent_mutation();

-- scan_events rows are written once; only the link to the record created in
-- the same transaction may be filled in afterwards.
create function app.scan_events_guard()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'scan_events is append-only' using errcode = 'insufficient_privilege';
  end if;
  if (to_jsonb(new) - 'attendance_record_id' - 'response') <> (to_jsonb(old) - 'attendance_record_id' - 'response') then
    raise exception 'scan_events is append-only' using errcode = 'insufficient_privilege';
  end if;
  return new;
end;
$$;

create trigger scan_events_append_only before update or delete on public.scan_events
  for each row execute function app.scan_events_guard();

-- ---------------------------------------------------------------------------
-- Generic audit trigger. Actor comes from the JWT (auth.uid()) or, for
-- device/system writes made by the server, from transaction-local settings:
--   app.actor_type, app.actor_device_id, app.audit_reason, app.request_id
-- Secrets (token_hash) are never copied into the audit log.
-- ---------------------------------------------------------------------------
create function app.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row        jsonb := to_jsonb(coalesce(new, old));
  v_before     jsonb := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) - 'token_hash' end;
  v_after      jsonb := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) - 'token_hash' end;
  v_user       uuid := auth.uid();
  v_actor_type public.actor_type;
  v_device     uuid := nullif(current_setting('app.actor_device_id', true), '')::uuid;
begin
  if tg_op = 'UPDATE' and v_before - 'updated_at' - 'version' = v_after - 'updated_at' - 'version' then
    return new;
  end if;

  v_actor_type := coalesce(
    nullif(current_setting('app.actor_type', true), '')::public.actor_type,
    case when v_user is not null then 'user' when v_device is not null then 'device' else 'system' end::public.actor_type
  );

  insert into public.audit_logs (
    school_id, actor_type, actor_user_id, actor_device_id,
    action, entity_type, entity_id, before, after, reason, request_id
  ) values (
    (v_row ->> 'school_id')::uuid,
    v_actor_type,
    v_user,
    v_device,
    lower(tg_op),
    tg_table_name,
    (v_row ->> 'id')::uuid,
    v_before,
    v_after,
    nullif(current_setting('app.audit_reason', true), ''),
    nullif(current_setting('app.request_id', true), '')
  );
  return coalesce(new, old);
end;
$$;

create trigger audit_attendance_records after insert or update or delete on public.attendance_records
  for each row execute function app.audit_row_change();
create trigger audit_nfc_credentials after insert or update or delete on public.nfc_credentials
  for each row execute function app.audit_row_change();
create trigger audit_devices after insert or update or delete on public.devices
  for each row execute function app.audit_row_change();
create trigger audit_attendance_rules after insert or update or delete on public.attendance_rules
  for each row execute function app.audit_row_change();
create trigger audit_school_memberships after insert or update or delete on public.school_memberships
  for each row execute function app.audit_row_change();
create trigger audit_enrollments after insert or update or delete on public.enrollments
  for each row execute function app.audit_row_change();

-- ---------------------------------------------------------------------------
-- New school bootstrap: default attendance rule + the simulator device.
-- ---------------------------------------------------------------------------
create function app.bootstrap_school()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.attendance_rules (school_id, name, is_default)
  values (new.id, 'Default', true);

  insert into public.devices (school_id, name, kind, location)
  values (new.id, 'NFC Simulator', 'simulator', 'Virtual');

  return new;
end;
$$;

create trigger schools_bootstrap after insert on public.schools
  for each row execute function app.bootstrap_school();

-- ====================================================================
-- 20260926000005_rls.sql
-- ====================================================================
-- Row Level Security and table privileges.
--
-- Model:
--   * anon: no access to any table.
--   * authenticated: table privileges are granted explicitly below and every
--     row is then filtered by RLS policies built on the app.* helpers.
--   * service_role (server only): bypasses RLS; used by the scan ingestion
--     path and trusted jobs, where the tenant is derived from a verified
--     credential. Composite FKs still enforce same-school references.
--   * Tables with no grant for a command (e.g. INSERT on attendance_records)
--     can only be written through SECURITY DEFINER RPCs or the server.

-- ---------------------------------------------------------------------------
-- Class-scoped helpers
-- ---------------------------------------------------------------------------

-- The caller is an active teacher (active membership + active teacher row)
-- currently assigned to the class section.
create function app.teaches_class(p_class_section_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.class_teachers ct
    join public.teachers t on t.id = ct.teacher_id and t.school_id = ct.school_id
    join public.school_memberships m
      on m.school_id = t.school_id and m.user_id = t.user_id
     and m.role = 'teacher' and m.status = 'active'
    where ct.class_section_id = p_class_section_id
      and t.user_id = auth.uid()
      and t.status = 'active'
      and (ct.valid_from is null or ct.valid_from <= current_date)
      and (ct.valid_to is null or ct.valid_to >= current_date)
  );
$$;

create function app.teaches_session(p_class_session_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.class_sessions s
    where s.id = p_class_session_id and app.teaches_class(s.class_section_id)
  );
$$;

-- The student is (or was) enrolled in a class the caller teaches.
create function app.teaches_student(p_student_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.enrollments e
    where e.student_id = p_student_id and app.teaches_class(e.class_section_id)
  );
$$;

-- Student rows linked to the caller's login (only via an active student membership).
create function app.is_my_student(p_student_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.students st
    join public.school_memberships m
      on m.school_id = st.school_id and m.user_id = st.user_id
     and m.role = 'student' and m.status = 'active'
    where st.id = p_student_id and st.user_id = auth.uid()
  );
$$;

create function app.is_enrolled_in(p_class_section_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.enrollments e
    where e.class_section_id = p_class_section_id and app.is_my_student(e.student_id)
  );
$$;

create function app.can_view_class(p_class_section_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.class_sections c
    where c.id = p_class_section_id
      and (app.is_admin(c.school_id)
           or app.teaches_class(c.id)
           or app.is_enrolled_in(c.id))
  );
$$;

-- Admins of any school the profile belongs to may see that profile.
create function app.can_view_profile(p_profile_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select p_profile_id = auth.uid()
      or app.is_platform_admin()
      or exists (
        select 1 from public.school_memberships m
        where m.user_id = p_profile_id and app.is_admin(m.school_id)
      );
$$;

revoke all on all functions in schema app from public;
grant execute on function
  app.is_platform_admin(),
  app.has_role(uuid, public.membership_role),
  app.is_member(uuid),
  app.is_admin(uuid),
  app.is_valid_timezone(text),
  app.teaches_class(uuid),
  app.teaches_session(uuid),
  app.teaches_student(uuid),
  app.is_my_student(uuid),
  app.is_enrolled_in(uuid),
  app.can_view_class(uuid),
  app.can_view_profile(uuid)
to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Privileges: start from nothing, then grant what each role needs.
-- ---------------------------------------------------------------------------
revoke all on all tables in schema public from anon, authenticated;
grant all on all tables in schema public to service_role;

grant select on public.schools to authenticated;
grant update (name, timezone, locale, settings) on public.schools to authenticated;

grant select on public.profiles to authenticated;
grant update (full_name) on public.profiles to authenticated;

grant select, delete on public.school_memberships to authenticated;
grant update (status) on public.school_memberships to authenticated;

grant select, insert, update, delete on
  public.students,
  public.teachers,
  public.attendance_rules,
  public.academic_terms,
  public.courses,
  public.class_sections,
  public.class_teachers,
  public.enrollments,
  public.class_schedules,
  public.class_sessions,
  public.nfc_credentials
to authenticated;

-- Devices: token_hash is never readable or writable by API users.
grant select (id, school_id, name, kind, status, location, room, class_section_id,
              token_last4, last_seen_at, metadata, created_at, updated_at)
  on public.devices to authenticated;
grant insert (school_id, name, location, room, class_section_id, metadata) on public.devices to authenticated;
grant update (name, status, location, room, class_section_id, metadata) on public.devices to authenticated;

-- Read-only for API users; written by the server / RPCs only.
grant select on public.attendance_records, public.scan_events, public.audit_logs to authenticated;

-- ---------------------------------------------------------------------------
-- Enable RLS everywhere
-- ---------------------------------------------------------------------------
alter table public.schools             enable row level security;
alter table public.profiles            enable row level security;
alter table public.school_memberships  enable row level security;
alter table public.students            enable row level security;
alter table public.teachers            enable row level security;
alter table public.attendance_rules    enable row level security;
alter table public.academic_terms      enable row level security;
alter table public.courses             enable row level security;
alter table public.class_sections      enable row level security;
alter table public.class_teachers      enable row level security;
alter table public.enrollments         enable row level security;
alter table public.class_schedules     enable row level security;
alter table public.class_sessions      enable row level security;
alter table public.devices             enable row level security;
alter table public.nfc_credentials     enable row level security;
alter table public.attendance_records  enable row level security;
alter table public.scan_events         enable row level security;
alter table public.audit_logs          enable row level security;

-- ---------------------------------------------------------------------------
-- Tenancy
-- ---------------------------------------------------------------------------
create policy schools_select on public.schools for select to authenticated
  using (app.is_member(id) or app.is_platform_admin());
create policy schools_update on public.schools for update to authenticated
  using (app.is_admin(id)) with check (app.is_admin(id));

create policy profiles_select on public.profiles for select to authenticated
  using (app.can_view_profile(id));
create policy profiles_update_self on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

create policy memberships_select on public.school_memberships for select to authenticated
  using (user_id = auth.uid() or app.is_admin(school_id));
create policy memberships_update on public.school_memberships for update to authenticated
  using (app.is_admin(school_id) and user_id <> auth.uid())
  with check (app.is_admin(school_id) and user_id <> auth.uid());
create policy memberships_delete on public.school_memberships for delete to authenticated
  using (app.is_admin(school_id) and user_id <> auth.uid());

-- ---------------------------------------------------------------------------
-- Admin-managed tables: admins have full CRUD within their school.
-- ---------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'students', 'teachers', 'attendance_rules', 'academic_terms', 'courses',
    'class_sections', 'class_teachers', 'enrollments', 'class_schedules',
    'class_sessions', 'devices', 'nfc_credentials'
  ] loop
    execute format(
      'create policy %1$s_admin_all on public.%1$I for all to authenticated
         using (app.is_admin(school_id)) with check (app.is_admin(school_id))', t);
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- Read access for teachers and students
-- ---------------------------------------------------------------------------
create policy students_select_teacher on public.students for select to authenticated
  using (app.teaches_student(id));
create policy students_select_self on public.students for select to authenticated
  using (app.is_my_student(id));

create policy teachers_select_member on public.teachers for select to authenticated
  using (app.is_member(school_id));

create policy attendance_rules_select_member on public.attendance_rules for select to authenticated
  using (app.is_member(school_id));
create policy academic_terms_select_member on public.academic_terms for select to authenticated
  using (app.is_member(school_id));
create policy courses_select_member on public.courses for select to authenticated
  using (app.is_member(school_id));

create policy class_sections_select on public.class_sections for select to authenticated
  using (app.teaches_class(id) or app.is_enrolled_in(id));
create policy class_teachers_select on public.class_teachers for select to authenticated
  using (app.can_view_class(class_section_id));
create policy class_schedules_select on public.class_schedules for select to authenticated
  using (app.can_view_class(class_section_id));
create policy class_sessions_select on public.class_sessions for select to authenticated
  using (app.can_view_class(class_section_id));

create policy enrollments_select_teacher on public.enrollments for select to authenticated
  using (app.teaches_class(class_section_id));
create policy enrollments_select_self on public.enrollments for select to authenticated
  using (app.is_my_student(student_id));

-- ---------------------------------------------------------------------------
-- Attendance data (read-only for API users)
-- ---------------------------------------------------------------------------
create policy attendance_records_select on public.attendance_records for select to authenticated
  using (
    app.is_admin(school_id)
    or app.teaches_session(class_session_id)
    or app.is_my_student(student_id)
  );

create policy scan_events_select on public.scan_events for select to authenticated
  using (
    app.is_admin(school_id)
    or (class_session_id is not null and app.teaches_session(class_session_id))
  );

create policy audit_logs_select on public.audit_logs for select to authenticated
  using (app.is_admin(school_id));

-- ====================================================================
-- 20260926000006_provisioning.sql
-- ====================================================================
-- Server-side provisioning RPCs. Executable by service_role only (the Next.js
-- server and operator scripts), never by browser sessions.

-- ---------------------------------------------------------------------------
-- provision_school: create a school and its first admin atomically.
-- Schools are never hard-deleted (audit logs are append-only), so creation
-- must not leave half-built tenants behind.
-- ---------------------------------------------------------------------------
create function public.provision_school(
  p_name text,
  p_slug text,
  p_timezone text,
  p_locale text,
  p_admin_user_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_school_id uuid;
begin
  if not exists (select 1 from public.profiles where id = p_admin_user_id) then
    raise exception 'admin user % has no profile', p_admin_user_id using errcode = 'foreign_key_violation';
  end if;

  perform set_config('app.actor_type', 'system', true);
  perform set_config('app.audit_reason', 'school provisioned', true);

  insert into public.schools (name, slug, timezone, locale)
  values (p_name, p_slug, p_timezone, coalesce(p_locale, 'es-CO'))
  returning id into v_school_id;

  insert into public.school_memberships (school_id, user_id, role, status)
  values (v_school_id, p_admin_user_id, 'school_admin', 'active');

  return v_school_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- generate_class_sessions: materialize dated sessions from recurring
-- schedules for [p_from, p_to] (school-local dates). Idempotent thanks to
-- unique (schedule_id, starts_at). Wall-clock times are converted with the
-- school's timezone, so DST shifts are handled by Postgres.
-- Returns the number of sessions created.
-- ---------------------------------------------------------------------------
create function public.generate_class_sessions(p_school_id uuid, p_from date, p_to date)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  if p_to < p_from then
    raise exception 'p_to must be on or after p_from';
  end if;
  if p_to - p_from > 120 then
    raise exception 'refusing to generate more than 120 days at once';
  end if;

  insert into public.class_sessions (school_id, class_section_id, schedule_id, starts_at, ends_at, room)
  select
    sch.school_id,
    sch.class_section_id,
    sch.id,
    (d.day + sch.start_time) at time zone s.timezone,
    (d.day + sch.end_time) at time zone s.timezone,
    coalesce(sch.room, c.room)
  from public.class_schedules sch
  join public.schools s on s.id = sch.school_id
  join public.class_sections c on c.id = sch.class_section_id and c.status = 'active'
  left join public.academic_terms t on t.id = c.term_id
  cross join lateral (
    select g::date as day
    from generate_series(
      greatest(p_from, sch.valid_from, coalesce(t.starts_on, p_from)),
      least(p_to, coalesce(sch.valid_to, p_to), coalesce(t.ends_on, p_to)),
      interval '1 day'
    ) g
  ) d
  where sch.school_id = p_school_id
    and extract(isodow from d.day) = sch.weekday
  on conflict (schedule_id, starts_at) do nothing;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.provision_school(text, text, text, text, uuid) from public, anon, authenticated;
revoke all on function public.generate_class_sessions(uuid, date, date) from public, anon, authenticated;
grant execute on function public.provision_school(text, text, text, text, uuid) to service_role;
grant execute on function public.generate_class_sessions(uuid, date, date) to service_role;

-- ====================================================================
-- 20260926000007_admin_rpcs.sql
-- ====================================================================
-- Phase 2: admin-callable RPCs for schedule management, plus a daily job that
-- keeps upcoming class sessions materialized.

-- ---------------------------------------------------------------------------
-- admin_generate_class_sessions: an admin (re)generates sessions for the next
-- p_days days of their own school. Idempotent.
-- ---------------------------------------------------------------------------
create function public.admin_generate_class_sessions(p_school_id uuid, p_days integer default 28)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_today date;
begin
  if not app.is_admin(p_school_id) then
    raise exception 'not an admin of this school' using errcode = 'insufficient_privilege';
  end if;
  if p_days not between 1 and 120 then
    raise exception 'p_days must be between 1 and 120';
  end if;

  select (now() at time zone s.timezone)::date into v_today
  from public.schools s where s.id = p_school_id;

  return public.generate_class_sessions(p_school_id, v_today, v_today + p_days);
end;
$$;

-- ---------------------------------------------------------------------------
-- remove_class_schedule: delete a recurring slot and its FUTURE sessions that
-- have no attendance yet. Past sessions and any session with attendance are
-- kept (their schedule_id becomes null). Returns the number of sessions removed.
-- ---------------------------------------------------------------------------
create function public.remove_class_schedule(p_schedule_id uuid)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_school_id uuid;
  v_count integer;
begin
  select school_id into v_school_id from public.class_schedules where id = p_schedule_id;
  if v_school_id is null or not app.is_admin(v_school_id) then
    raise exception 'schedule not found' using errcode = 'insufficient_privilege';
  end if;

  delete from public.class_sessions cs
  where cs.schedule_id = p_schedule_id
    and cs.starts_at > now()
    and not exists (select 1 from public.attendance_records ar where ar.class_session_id = cs.id)
    and not exists (select 1 from public.scan_events se where se.class_session_id = cs.id);
  get diagnostics v_count = row_count;

  delete from public.class_schedules where id = p_schedule_id;
  return v_count;
end;
$$;

-- ---------------------------------------------------------------------------
-- generate_upcoming_sessions: for every active school, materialize sessions
-- for the next p_days days (in each school's own timezone). Run daily.
-- ---------------------------------------------------------------------------
create function public.generate_upcoming_sessions(p_days integer default 28)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  s record;
  v_total integer := 0;
  v_today date;
begin
  for s in select id, timezone from public.schools where status = 'active' loop
    v_today := (now() at time zone s.timezone)::date;
    v_total := v_total + public.generate_class_sessions(s.id, v_today, v_today + p_days);
  end loop;
  return v_total;
end;
$$;

revoke all on function public.admin_generate_class_sessions(uuid, integer) from public, anon;
revoke all on function public.remove_class_schedule(uuid) from public, anon;
revoke all on function public.generate_upcoming_sessions(integer) from public, anon, authenticated;
grant execute on function public.admin_generate_class_sessions(uuid, integer) to authenticated, service_role;
grant execute on function public.remove_class_schedule(uuid) to authenticated, service_role;
grant execute on function public.generate_upcoming_sessions(integer) to service_role;

-- ---------------------------------------------------------------------------
-- Daily job (Supabase ships pg_cron). Skipped where pg_cron isn't available,
-- e.g. the plain-Postgres test database.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron with schema pg_catalog;
    perform cron.schedule(
      'generate-upcoming-class-sessions',
      '17 7 * * *',  -- daily 07:17 UTC (02:17 in Bogota)
      'select public.generate_upcoming_sessions(28)'
    );
  end if;
exception when others then
  -- Never fail the migration over the scheduler; sessions can still be
  -- generated from the admin UI. Enable pg_cron in the dashboard and re-run
  -- this block to get the daily job.
  raise notice 'pg_cron job not scheduled: %', sqlerrm;
end;
$$;

-- ====================================================================
-- 20260926000008_attendance_engine.sql
-- ====================================================================
-- Phase 3: the attendance engine.
--
-- process_scan() is the ONE place where a card tap becomes attendance. Every
-- entry point (registered NFC readers, the simulator) authenticates the caller
-- in the API layer and then calls this function with a verified device id.
-- It runs in a single transaction, so each tap is all-or-nothing and two
-- simultaneous taps can never create two records.
--
-- finalize_due_sessions() marks enrolled students without a scan as absent
-- once a session passes its absence cutoff.

-- ---------------------------------------------------------------------------
-- Effective attendance rule of a session: its frozen snapshot, else the
-- class override, else the school default.
-- ---------------------------------------------------------------------------
create function app.session_rule(p_session_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    cs.rule_snapshot,
    (select to_jsonb(r) from public.attendance_rules r where r.id = c.attendance_rule_id),
    (select to_jsonb(r) from public.attendance_rules r where r.school_id = cs.school_id and r.is_default)
  )
  from public.class_sessions cs
  join public.class_sections c on c.id = cs.class_section_id
  where cs.id = p_session_id;
$$;

-- Is the student enrolled in the class on the given (school-local) date?
create function app.enrolled_on(p_student_id uuid, p_class_section_id uuid, p_day date)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.enrollments e
    where e.student_id = p_student_id
      and e.class_section_id = p_class_section_id
      and e.enrolled_on <= p_day
      and (e.withdrawn_on is null or e.withdrawn_on > p_day)
  );
$$;

-- ---------------------------------------------------------------------------
-- process_scan
-- ---------------------------------------------------------------------------
create function public.process_scan(
  p_device_id uuid,
  p_uid text,
  p_idempotency_key text,
  p_effective_at timestamptz,
  p_device_scanned_at timestamptz default null,
  p_request_id text default null,
  p_detail text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid text := upper(regexp_replace(coalesce(p_uid, ''), '[\s:.-]', '', 'g'));
  v_device public.devices%rowtype;
  v_school public.schools%rowtype;
  v_existing public.scan_events%rowtype;
  v_default_rule public.attendance_rules%rowtype;
  v_credential_id uuid;
  v_student public.students%rowtype;
  v_student_found boolean := false;
  v_session_id uuid;
  v_session_starts timestamptz;
  v_class_name text;
  v_next_starts timestamptz;
  v_next_class text;
  v_rule jsonb;
  v_day date;
  v_delta_min numeric;
  v_status public.attendance_status;
  v_outcome public.scan_outcome;
  v_detail text := p_detail;
  v_record public.attendance_records%rowtype;
  v_record_found boolean := false;
  v_scan_id uuid;
  v_feedback text;
  v_message text;
  v_response jsonb;
  v_dash constant text := ' ' || chr(8212) || ' ';  -- em dash, kept ASCII-only in source
begin
  -- Idempotency: one result per (device, key), even under concurrent retries.
  perform pg_advisory_xact_lock(hashtextextended(p_device_id::text || '|' || p_idempotency_key, 0));
  select * into v_existing
  from public.scan_events
  where device_id = p_device_id and idempotency_key = p_idempotency_key;
  if found then
    if v_existing.uid_normalized <> v_uid then
      return jsonb_build_object('error', 'idempotency_conflict');
    end if;
    return v_existing.response || jsonb_build_object('replayed', true);
  end if;

  select * into v_device from public.devices where id = p_device_id;
  if not found then
    raise exception 'unknown device %', p_device_id using errcode = 'no_data_found';
  end if;
  select * into v_school from public.schools where id = v_device.school_id;
  select * into v_default_rule from public.attendance_rules where school_id = v_school.id and is_default;
  v_day := (p_effective_at at time zone v_school.timezone)::date;

  -- Attribute every write in this transaction to the device (audit trigger).
  perform set_config('app.actor_type', 'device', true);
  perform set_config('app.actor_device_id', p_device_id::text, true);
  perform set_config('app.request_id', coalesce(p_request_id, ''), true);

  -- 1. Device / school state
  if v_device.status <> 'active' then
    v_outcome := 'device_disabled';
  elsif v_school.status <> 'active' then
    v_outcome := 'school_suspended';
  elsif v_uid !~ '^([0-9A-F]{8}|[0-9A-F]{14}|[0-9A-F]{20})$' then
    v_outcome := 'unknown_credential';
    v_detail := coalesce(v_detail, 'malformed uid');
  end if;

  -- 2. Identify the student. The credential must belong to the DEVICE's
  --    school, so a card from another school is simply unknown here.
  if v_outcome is null then
    select c.id into v_credential_id
    from public.nfc_credentials c
    where c.school_id = v_school.id and c.uid_normalized = v_uid and c.status = 'active';

    if v_credential_id is null then
      v_outcome := case
        when exists (select 1 from public.nfc_credentials c where c.school_id = v_school.id and c.uid_normalized = v_uid)
          then 'inactive_credential'::public.scan_outcome
        else 'unknown_credential'::public.scan_outcome
      end;
    else
      select s.* into v_student
      from public.students s
      join public.nfc_credentials c on c.student_id = s.id
      where c.id = v_credential_id;
      v_student_found := true;
      if v_student.status <> 'active' then
        v_outcome := 'inactive_student';
      end if;
    end if;
  end if;

  -- 3. Debounce: the same card on the same reader within the window is a repeat.
  if v_outcome is null and exists (
    select 1 from public.scan_events se
    where se.device_id = p_device_id
      and se.uid_normalized = v_uid
      and se.outcome in ('recorded', 'duplicate')
      and se.received_at > now() - make_interval(secs => v_default_rule.duplicate_window_seconds)
  ) then
    select ar.* into v_record
    from public.scan_events se
    join public.attendance_records ar on ar.id = se.attendance_record_id
    where se.device_id = p_device_id and se.uid_normalized = v_uid
    order by se.received_at desc
    limit 1;
    v_record_found := found;
    v_outcome := 'duplicate';
    v_detail := coalesce(v_detail, 'repeated tap');
    if v_record_found then
      select cs.id, c.name into v_session_id, v_class_name
      from public.class_sessions cs join public.class_sections c on c.id = cs.class_section_id
      where cs.id = v_record.class_session_id;
    end if;
  end if;

  -- 4. Which session should the student be in right now?
  if v_outcome is null then
    select cs.id, cs.starts_at, c.name, app.session_rule(cs.id)
    into v_session_id, v_session_starts, v_class_name, v_rule
    from public.class_sessions cs
    join public.class_sections c on c.id = cs.class_section_id and c.status = 'active'
    where cs.school_id = v_school.id
      and cs.status = 'scheduled'
      and (v_device.class_section_id is null or cs.class_section_id = v_device.class_section_id)
      and app.enrolled_on(v_student.id, cs.class_section_id, (cs.starts_at at time zone v_school.timezone)::date)
      and p_effective_at >= cs.starts_at - make_interval(mins => (app.session_rule(cs.id) ->> 'early_checkin_minutes')::int)
      and p_effective_at <= greatest(cs.ends_at, cs.starts_at + make_interval(mins => (app.session_rule(cs.id) ->> 'absent_after_minutes')::int))
    order by
      exists (                                                  -- sessions not already attended first
        select 1 from public.attendance_records ar
        where ar.class_session_id = cs.id and ar.student_id = v_student.id and ar.source <> 'system'
      ),
      (p_effective_at >= cs.ends_at),                           -- then sessions still running
      abs(extract(epoch from (cs.starts_at - p_effective_at))), -- then the nearest start
      cs.id
    limit 1;

    if v_session_id is null then
      if v_device.class_section_id is not null and exists (
        select 1 from public.class_sessions cs
        where cs.class_section_id = v_device.class_section_id and cs.status = 'scheduled'
          and p_effective_at between cs.starts_at - interval '1 hour' and cs.ends_at
      ) then
        v_outcome := 'not_enrolled';
        select c.name into v_detail from public.class_sections c where c.id = v_device.class_section_id;
      else
        -- A class of theirs later today -> too early; otherwise nothing now.
        select cs.starts_at, c.name into v_next_starts, v_next_class
        from public.class_sessions cs
        join public.class_sections c on c.id = cs.class_section_id and c.status = 'active'
        where cs.school_id = v_school.id and cs.status = 'scheduled'
          and cs.starts_at > p_effective_at
          and (cs.starts_at at time zone v_school.timezone)::date = v_day
          and (v_device.class_section_id is null or cs.class_section_id = v_device.class_section_id)
          and app.enrolled_on(v_student.id, cs.class_section_id, v_day)
        order by cs.starts_at
        limit 1;
        v_outcome := case when v_next_starts is not null then 'too_early'::public.scan_outcome else 'no_active_session'::public.scan_outcome end;
      end if;
    end if;
  end if;

  -- 5. Classify against the session's rule.
  if v_outcome is null then
    v_delta_min := extract(epoch from (p_effective_at - v_session_starts)) / 60.0;
    if v_delta_min <= (v_rule ->> 'late_after_minutes')::int then
      v_status := 'present';
    elsif v_delta_min <= (v_rule ->> 'absent_after_minutes')::int then
      v_status := 'late';
    else
      case v_rule ->> 'scan_after_cutoff'
        when 'late' then v_status := 'late';
        when 'absent' then v_status := 'absent'; v_outcome := 'after_cutoff';
        else v_outcome := 'after_cutoff'; -- reject: logged, no record
      end case;
    end if;

    -- Freeze the rule for this session on its first scan.
    update public.class_sessions set rule_snapshot = v_rule where id = v_session_id and rule_snapshot is null;
  end if;

  -- 6. One record per student per session (serialized per pair).
  if v_status is not null then
    perform pg_advisory_xact_lock(hashtextextended(v_session_id::text || '|' || v_student.id::text, 1));
    select * into v_record from public.attendance_records
    where class_session_id = v_session_id and student_id = v_student.id;
    v_record_found := found;

    if v_record_found then
      if not v_record.is_manual_override and v_record.status = 'absent' and v_record.source = 'system'
         and v_status in ('present', 'late') then
        v_outcome := 'recorded';       -- arrived after the absence was auto-marked
        v_detail := coalesce(v_detail, 'replaced automatic absence');
      else
        v_outcome := 'duplicate';      -- already recorded (or a teacher decided): keep it
        v_status := null;
      end if;
    else
      v_outcome := coalesce(v_outcome, 'recorded');
    end if;
  end if;

  -- 7. Log the tap (append-only) ...
  insert into public.scan_events (
    school_id, device_id, idempotency_key, uid_normalized, credential_id, student_id,
    class_session_id, device_scanned_at, effective_at, outcome, outcome_detail, request_id
  ) values (
    v_school.id, p_device_id, p_idempotency_key, v_uid, v_credential_id,
    case when v_student_found then v_student.id end,
    v_session_id, p_device_scanned_at, p_effective_at, v_outcome, v_detail, p_request_id
  )
  returning id into v_scan_id;

  -- ... then write the attendance record.
  if v_status is not null then
    if v_record_found then
      update public.attendance_records
      set status = v_status, source = 'nfc', checked_in_at = p_effective_at, first_scan_event_id = v_scan_id, updated_by = null
      where id = v_record.id
      returning * into v_record;
    else
      insert into public.attendance_records (
        school_id, class_session_id, student_id, status, source, checked_in_at, first_scan_event_id
      ) values (
        v_school.id, v_session_id, v_student.id, v_status, 'nfc', p_effective_at, v_scan_id
      )
      on conflict (class_session_id, student_id) do nothing
      returning * into v_record;
      if not found then
        -- The absence job inserted concurrently; its row is 'absent'/'system'.
        update public.attendance_records
        set status = v_status, source = 'nfc', checked_in_at = p_effective_at, first_scan_event_id = v_scan_id
        where class_session_id = v_session_id and student_id = v_student.id
          and source = 'system' and not is_manual_override
        returning * into v_record;
      end if;
    end if;
    v_record_found := v_record.id is not null;
  end if;

  -- 8. Build the response a reader (or the simulator) shows.
  v_feedback := case
    when v_outcome = 'recorded' and v_record.status = 'present' then 'accept'
    when v_outcome in ('recorded', 'duplicate') then 'warn'
    when v_outcome = 'after_cutoff' and v_record_found then 'warn'
    else 'reject'
  end;
  v_message := case v_outcome
    when 'recorded' then initcap(v_record.status::text) || v_dash || v_class_name
    when 'duplicate' then 'Already checked in' || coalesce(v_dash || v_class_name, '')
    when 'after_cutoff' then case when v_record_found then 'Too late, marked absent' else 'Too late, scan rejected' end || v_dash || v_class_name
    when 'unknown_credential' then 'Unknown card'
    when 'inactive_credential' then 'This card is no longer active'
    when 'inactive_student' then 'Student is not active'
    when 'no_active_session' then 'No class right now'
    when 'too_early' then 'Too early' || v_dash || v_next_class || ' starts at '
      || to_char(v_next_starts at time zone v_school.timezone, 'HH24:MI')
    when 'not_enrolled' then 'Not enrolled in ' || coalesce(v_detail, 'this class')
    when 'device_disabled' then 'This reader is disabled'
    when 'school_suspended' then 'School account suspended'
  end;

  v_response := jsonb_build_object(
    'scan_id', v_scan_id,
    'outcome', v_outcome,
    'feedback', v_feedback,
    'message', v_message,
    'effective_at', p_effective_at,
    'attendance', case when v_record_found then jsonb_build_object(
      'record_id', v_record.id,
      'status', v_record.status,
      'class_session_id', v_record.class_session_id,
      'class_name', v_class_name,
      'checked_in_at', v_record.checked_in_at
    ) end,
    'student', case when v_student_found then jsonb_build_object(
      'display_name', v_student.first_name || ' ' || left(v_student.last_name, 1) || '.'
    ) end
  );

  update public.scan_events
  set attendance_record_id = case when v_record_found then v_record.id end, response = v_response
  where id = v_scan_id;

  update public.devices set last_seen_at = now() where id = p_device_id;

  return v_response;
end;
$$;

-- ---------------------------------------------------------------------------
-- finalize_due_sessions: after a session's absence cutoff, every student who
-- was enrolled that day and has no record is marked absent (source=system).
-- Idempotent and safe to run concurrently with scans.
-- ---------------------------------------------------------------------------
create function public.finalize_due_sessions(p_school_id uuid default null)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  s record;
  v_rule jsonb;
  v_day date;
  v_count integer := 0;
begin
  perform set_config('app.actor_type', 'system', true);
  perform set_config('app.audit_reason', 'no scan before the absence cutoff', true);

  for s in
    select cs.id, cs.school_id, cs.class_section_id, cs.starts_at, sch.timezone
    from public.class_sessions cs
    join public.schools sch on sch.id = cs.school_id and sch.status = 'active'
    where cs.status = 'scheduled'
      and cs.finalized_at is null
      and cs.starts_at < now()
      and (p_school_id is null or cs.school_id = p_school_id)
    order by cs.starts_at
    for update of cs skip locked
  loop
    v_rule := app.session_rule(s.id);
    continue when now() < s.starts_at + make_interval(mins => (v_rule ->> 'absent_after_minutes')::int);

    v_day := (s.starts_at at time zone s.timezone)::date;
    if coalesce((v_rule ->> 'auto_finalize')::boolean, true) then
      insert into public.attendance_records (school_id, class_session_id, student_id, status, source)
      select s.school_id, s.id, e.student_id, 'absent', 'system'
      from public.enrollments e
      join public.students st on st.id = e.student_id and st.status = 'active'
      where e.class_section_id = s.class_section_id
        and e.enrolled_on <= v_day
        and (e.withdrawn_on is null or e.withdrawn_on > v_day)
      on conflict (class_session_id, student_id) do nothing;
    end if;

    update public.class_sessions
    set finalized_at = now(), rule_snapshot = coalesce(rule_snapshot, v_rule)
    where id = s.id;
    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;

-- Admin-triggered run for one school (e.g. from the simulator page).
create function public.admin_finalize_due_sessions(p_school_id uuid)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not app.is_admin(p_school_id) then
    raise exception 'not an admin of this school' using errcode = 'insufficient_privilege';
  end if;
  return public.finalize_due_sessions(p_school_id);
end;
$$;

-- ---------------------------------------------------------------------------
-- Reader tokens: the server generates the token and passes only its SHA-256.
-- ---------------------------------------------------------------------------
create function public.admin_set_device_token(p_device_id uuid, p_token_hash text, p_token_last4 text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_school_id uuid;
begin
  select school_id into v_school_id from public.devices where id = p_device_id and kind = 'reader';
  if v_school_id is null or not app.is_admin(v_school_id) then
    raise exception 'reader not found' using errcode = 'insufficient_privilege';
  end if;
  if p_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid token hash';
  end if;
  update public.devices set token_hash = p_token_hash, token_last4 = p_token_last4 where id = p_device_id;
end;
$$;

revoke all on function app.session_rule(uuid) from public;
revoke all on function app.enrolled_on(uuid, uuid, date) from public;
revoke all on function public.process_scan(uuid, text, text, timestamptz, timestamptz, text, text) from public, anon, authenticated;
revoke all on function public.finalize_due_sessions(uuid) from public, anon, authenticated;
revoke all on function public.admin_finalize_due_sessions(uuid) from public, anon;
revoke all on function public.admin_set_device_token(uuid, text, text) from public, anon;

grant execute on function public.process_scan(uuid, text, text, timestamptz, timestamptz, text, text) to service_role;
grant execute on function public.finalize_due_sessions(uuid) to service_role;
grant execute on function public.admin_finalize_due_sessions(uuid) to authenticated, service_role;
grant execute on function public.admin_set_device_token(uuid, text, text) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Absence job every 5 minutes (skipped where pg_cron isn't available).
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron with schema pg_catalog;
    perform cron.schedule('finalize-due-sessions', '*/5 * * * *', 'select public.finalize_due_sessions()');
  end if;
exception when others then
  raise notice 'pg_cron job not scheduled: %', sqlerrm;
end;
$$;

-- ====================================================================
-- 20260926000009_ascii_scan_messages.sql
-- ====================================================================
-- Re-creates public.process_scan from migration 8 with an ASCII-only source.
-- Databases set up by pasting SQL through tools that re-encode UTF-8 could end
-- up with a garbled em dash in scan messages; this replaces the function body.
-- Privileges are kept by CREATE OR REPLACE.

create or replace function public.process_scan(
  p_device_id uuid,
  p_uid text,
  p_idempotency_key text,
  p_effective_at timestamptz,
  p_device_scanned_at timestamptz default null,
  p_request_id text default null,
  p_detail text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid text := upper(regexp_replace(coalesce(p_uid, ''), '[\s:.-]', '', 'g'));
  v_device public.devices%rowtype;
  v_school public.schools%rowtype;
  v_existing public.scan_events%rowtype;
  v_default_rule public.attendance_rules%rowtype;
  v_credential_id uuid;
  v_student public.students%rowtype;
  v_student_found boolean := false;
  v_session_id uuid;
  v_session_starts timestamptz;
  v_class_name text;
  v_next_starts timestamptz;
  v_next_class text;
  v_rule jsonb;
  v_day date;
  v_delta_min numeric;
  v_status public.attendance_status;
  v_outcome public.scan_outcome;
  v_detail text := p_detail;
  v_record public.attendance_records%rowtype;
  v_record_found boolean := false;
  v_scan_id uuid;
  v_feedback text;
  v_message text;
  v_response jsonb;
  v_dash constant text := ' ' || chr(8212) || ' ';  -- em dash, kept ASCII-only in source
begin
  -- Idempotency: one result per (device, key), even under concurrent retries.
  perform pg_advisory_xact_lock(hashtextextended(p_device_id::text || '|' || p_idempotency_key, 0));
  select * into v_existing
  from public.scan_events
  where device_id = p_device_id and idempotency_key = p_idempotency_key;
  if found then
    if v_existing.uid_normalized <> v_uid then
      return jsonb_build_object('error', 'idempotency_conflict');
    end if;
    return v_existing.response || jsonb_build_object('replayed', true);
  end if;

  select * into v_device from public.devices where id = p_device_id;
  if not found then
    raise exception 'unknown device %', p_device_id using errcode = 'no_data_found';
  end if;
  select * into v_school from public.schools where id = v_device.school_id;
  select * into v_default_rule from public.attendance_rules where school_id = v_school.id and is_default;
  v_day := (p_effective_at at time zone v_school.timezone)::date;

  -- Attribute every write in this transaction to the device (audit trigger).
  perform set_config('app.actor_type', 'device', true);
  perform set_config('app.actor_device_id', p_device_id::text, true);
  perform set_config('app.request_id', coalesce(p_request_id, ''), true);

  -- 1. Device / school state
  if v_device.status <> 'active' then
    v_outcome := 'device_disabled';
  elsif v_school.status <> 'active' then
    v_outcome := 'school_suspended';
  elsif v_uid !~ '^([0-9A-F]{8}|[0-9A-F]{14}|[0-9A-F]{20})$' then
    v_outcome := 'unknown_credential';
    v_detail := coalesce(v_detail, 'malformed uid');
  end if;

  -- 2. Identify the student. The credential must belong to the DEVICE's
  --    school, so a card from another school is simply unknown here.
  if v_outcome is null then
    select c.id into v_credential_id
    from public.nfc_credentials c
    where c.school_id = v_school.id and c.uid_normalized = v_uid and c.status = 'active';

    if v_credential_id is null then
      v_outcome := case
        when exists (select 1 from public.nfc_credentials c where c.school_id = v_school.id and c.uid_normalized = v_uid)
          then 'inactive_credential'::public.scan_outcome
        else 'unknown_credential'::public.scan_outcome
      end;
    else
      select s.* into v_student
      from public.students s
      join public.nfc_credentials c on c.student_id = s.id
      where c.id = v_credential_id;
      v_student_found := true;
      if v_student.status <> 'active' then
        v_outcome := 'inactive_student';
      end if;
    end if;
  end if;

  -- 3. Debounce: the same card on the same reader within the window is a repeat.
  if v_outcome is null and exists (
    select 1 from public.scan_events se
    where se.device_id = p_device_id
      and se.uid_normalized = v_uid
      and se.outcome in ('recorded', 'duplicate')
      and se.received_at > now() - make_interval(secs => v_default_rule.duplicate_window_seconds)
  ) then
    select ar.* into v_record
    from public.scan_events se
    join public.attendance_records ar on ar.id = se.attendance_record_id
    where se.device_id = p_device_id and se.uid_normalized = v_uid
    order by se.received_at desc
    limit 1;
    v_record_found := found;
    v_outcome := 'duplicate';
    v_detail := coalesce(v_detail, 'repeated tap');
    if v_record_found then
      select cs.id, c.name into v_session_id, v_class_name
      from public.class_sessions cs join public.class_sections c on c.id = cs.class_section_id
      where cs.id = v_record.class_session_id;
    end if;
  end if;

  -- 4. Which session should the student be in right now?
  if v_outcome is null then
    select cs.id, cs.starts_at, c.name, app.session_rule(cs.id)
    into v_session_id, v_session_starts, v_class_name, v_rule
    from public.class_sessions cs
    join public.class_sections c on c.id = cs.class_section_id and c.status = 'active'
    where cs.school_id = v_school.id
      and cs.status = 'scheduled'
      and (v_device.class_section_id is null or cs.class_section_id = v_device.class_section_id)
      and app.enrolled_on(v_student.id, cs.class_section_id, (cs.starts_at at time zone v_school.timezone)::date)
      and p_effective_at >= cs.starts_at - make_interval(mins => (app.session_rule(cs.id) ->> 'early_checkin_minutes')::int)
      and p_effective_at <= greatest(cs.ends_at, cs.starts_at + make_interval(mins => (app.session_rule(cs.id) ->> 'absent_after_minutes')::int))
    order by
      exists (                                                  -- sessions not already attended first
        select 1 from public.attendance_records ar
        where ar.class_session_id = cs.id and ar.student_id = v_student.id and ar.source <> 'system'
      ),
      (p_effective_at >= cs.ends_at),                           -- then sessions still running
      abs(extract(epoch from (cs.starts_at - p_effective_at))), -- then the nearest start
      cs.id
    limit 1;

    if v_session_id is null then
      if v_device.class_section_id is not null and exists (
        select 1 from public.class_sessions cs
        where cs.class_section_id = v_device.class_section_id and cs.status = 'scheduled'
          and p_effective_at between cs.starts_at - interval '1 hour' and cs.ends_at
      ) then
        v_outcome := 'not_enrolled';
        select c.name into v_detail from public.class_sections c where c.id = v_device.class_section_id;
      else
        -- A class of theirs later today -> too early; otherwise nothing now.
        select cs.starts_at, c.name into v_next_starts, v_next_class
        from public.class_sessions cs
        join public.class_sections c on c.id = cs.class_section_id and c.status = 'active'
        where cs.school_id = v_school.id and cs.status = 'scheduled'
          and cs.starts_at > p_effective_at
          and (cs.starts_at at time zone v_school.timezone)::date = v_day
          and (v_device.class_section_id is null or cs.class_section_id = v_device.class_section_id)
          and app.enrolled_on(v_student.id, cs.class_section_id, v_day)
        order by cs.starts_at
        limit 1;
        v_outcome := case when v_next_starts is not null then 'too_early'::public.scan_outcome else 'no_active_session'::public.scan_outcome end;
      end if;
    end if;
  end if;

  -- 5. Classify against the session's rule.
  if v_outcome is null then
    v_delta_min := extract(epoch from (p_effective_at - v_session_starts)) / 60.0;
    if v_delta_min <= (v_rule ->> 'late_after_minutes')::int then
      v_status := 'present';
    elsif v_delta_min <= (v_rule ->> 'absent_after_minutes')::int then
      v_status := 'late';
    else
      case v_rule ->> 'scan_after_cutoff'
        when 'late' then v_status := 'late';
        when 'absent' then v_status := 'absent'; v_outcome := 'after_cutoff';
        else v_outcome := 'after_cutoff'; -- reject: logged, no record
      end case;
    end if;

    -- Freeze the rule for this session on its first scan.
    update public.class_sessions set rule_snapshot = v_rule where id = v_session_id and rule_snapshot is null;
  end if;

  -- 6. One record per student per session (serialized per pair).
  if v_status is not null then
    perform pg_advisory_xact_lock(hashtextextended(v_session_id::text || '|' || v_student.id::text, 1));
    select * into v_record from public.attendance_records
    where class_session_id = v_session_id and student_id = v_student.id;
    v_record_found := found;

    if v_record_found then
      if not v_record.is_manual_override and v_record.status = 'absent' and v_record.source = 'system'
         and v_status in ('present', 'late') then
        v_outcome := 'recorded';       -- arrived after the absence was auto-marked
        v_detail := coalesce(v_detail, 'replaced automatic absence');
      else
        v_outcome := 'duplicate';      -- already recorded (or a teacher decided): keep it
        v_status := null;
      end if;
    else
      v_outcome := coalesce(v_outcome, 'recorded');
    end if;
  end if;

  -- 7. Log the tap (append-only) ...
  insert into public.scan_events (
    school_id, device_id, idempotency_key, uid_normalized, credential_id, student_id,
    class_session_id, device_scanned_at, effective_at, outcome, outcome_detail, request_id
  ) values (
    v_school.id, p_device_id, p_idempotency_key, v_uid, v_credential_id,
    case when v_student_found then v_student.id end,
    v_session_id, p_device_scanned_at, p_effective_at, v_outcome, v_detail, p_request_id
  )
  returning id into v_scan_id;

  -- ... then write the attendance record.
  if v_status is not null then
    if v_record_found then
      update public.attendance_records
      set status = v_status, source = 'nfc', checked_in_at = p_effective_at, first_scan_event_id = v_scan_id, updated_by = null
      where id = v_record.id
      returning * into v_record;
    else
      insert into public.attendance_records (
        school_id, class_session_id, student_id, status, source, checked_in_at, first_scan_event_id
      ) values (
        v_school.id, v_session_id, v_student.id, v_status, 'nfc', p_effective_at, v_scan_id
      )
      on conflict (class_session_id, student_id) do nothing
      returning * into v_record;
      if not found then
        -- The absence job inserted concurrently; its row is 'absent'/'system'.
        update public.attendance_records
        set status = v_status, source = 'nfc', checked_in_at = p_effective_at, first_scan_event_id = v_scan_id
        where class_session_id = v_session_id and student_id = v_student.id
          and source = 'system' and not is_manual_override
        returning * into v_record;
      end if;
    end if;
    v_record_found := v_record.id is not null;
  end if;

  -- 8. Build the response a reader (or the simulator) shows.
  v_feedback := case
    when v_outcome = 'recorded' and v_record.status = 'present' then 'accept'
    when v_outcome in ('recorded', 'duplicate') then 'warn'
    when v_outcome = 'after_cutoff' and v_record_found then 'warn'
    else 'reject'
  end;
  v_message := case v_outcome
    when 'recorded' then initcap(v_record.status::text) || v_dash || v_class_name
    when 'duplicate' then 'Already checked in' || coalesce(v_dash || v_class_name, '')
    when 'after_cutoff' then case when v_record_found then 'Too late, marked absent' else 'Too late, scan rejected' end || v_dash || v_class_name
    when 'unknown_credential' then 'Unknown card'
    when 'inactive_credential' then 'This card is no longer active'
    when 'inactive_student' then 'Student is not active'
    when 'no_active_session' then 'No class right now'
    when 'too_early' then 'Too early' || v_dash || v_next_class || ' starts at '
      || to_char(v_next_starts at time zone v_school.timezone, 'HH24:MI')
    when 'not_enrolled' then 'Not enrolled in ' || coalesce(v_detail, 'this class')
    when 'device_disabled' then 'This reader is disabled'
    when 'school_suspended' then 'School account suspended'
  end;

  v_response := jsonb_build_object(
    'scan_id', v_scan_id,
    'outcome', v_outcome,
    'feedback', v_feedback,
    'message', v_message,
    'effective_at', p_effective_at,
    'attendance', case when v_record_found then jsonb_build_object(
      'record_id', v_record.id,
      'status', v_record.status,
      'class_session_id', v_record.class_session_id,
      'class_name', v_class_name,
      'checked_in_at', v_record.checked_in_at
    ) end,
    'student', case when v_student_found then jsonb_build_object(
      'display_name', v_student.first_name || ' ' || left(v_student.last_name, 1) || '.'
    ) end
  );

  update public.scan_events
  set attendance_record_id = case when v_record_found then v_record.id end, response = v_response
  where id = v_scan_id;

  update public.devices set last_seen_at = now() where id = p_device_id;

  return v_response;
end;
$$;

commit;
